### ISSUE TITLE
v0.10.0 might be broken

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lucid#121]
https://github.com/pcdshub/lucid/actions/runs/4611506140

**Comment by ZLLentz** [comment]
This appears to be unrelated to any of the content in lucid. I'm going to re-run these jobs and see if they behave better.
The only unexpected failure is conda py3.9 which fails with the cryptic:
```
Reloading output folder: /home/runner/conda-bld
Traceback (most recent call last):
  File "/home/runner/micromamba/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/home/runner/micromamba/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/home/runner/micromamba/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/home/runner/micromamba/lib/python3.9/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/home/runner/micromamba/lib/python3.9/site-packages/conda_build/build.py", line 3089, in build_tree
    test(pkg, config=metadata.config.copy(), stats=stats)
  File "/home/runner/micromamba/lib/python3.9/site-packages/conda_build/build.py", line [287](https://github.com/pcdshub/lucid/actions/runs/4611506140/jobs/8151274739#step:12:288)9, in test
    environ.create_env(metadata.config.test_prefix, actions, config=metadata.config,
  File "/home/runner/micromamba/lib/python3.9/site-packages/conda_build/environ.py", line 1052, in create_env
    display_actions(actions, index)
  File "/home/runner/micromamba/lib/python3.9/site-packages/conda/exports.py", line 204, in display_actions
    actions['LINK'] = [index[d] for d in actions['LINK']]
  File "/home/runner/micromamba/lib/python3.9/site-packages/conda/exports.py", line 204, in <listcomp>
    actions['LINK'] = [index[d] for d in actions['LINK']]
KeyError: Dist(channel='conda-forge', dist_name='pytz-2023.3-pyhd8ed1ab_0', name='pytz', fmt='.conda', version='2023.3', build_string='pyhd8ed1ab_0', build_number=0, base_url=None, platform=None)
Error: Process completed with exit code 1.
```
Which implies that something went wrong internally in conda?
I think it's worth a re-run.

**Comment by ZLLentz** [comment]
The python 3.9 build passed on the re-run, so I'm confident that v0.10.0 should work OK and it should be OK to merge the conda-forge PR for it.
