### ISSUE TITLE
Embedded display intermittent issue (`object of type 'NoneType' has no len()`)

### ISSUE THREAD

**Issue by klauer** [pcdshub/lucid#78]
While loading the attenuator calculator screen (and maybe popping it out too quickly?)

```
[2020-08-04 14:06:14,573] [ERROR   ] - An uncaught exception happened: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/reg/g/pcds/pyps/conda/py36/envs/dev/bin/lucid", line 10, in <module>
    sys.exit(main())
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/lucid/launcher.py", line 237, in main
    launch(**kwargs)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/lucid/launcher.py", line 231, in launch
    app.exec_()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/lucid/overview.py", line 107, in eventFilter
    self.device_menu.exec_(self.mapToGlobal(event.pos()))
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/lucid/main_window.py", line 379, in wrapper
    area=QtAds.RightDockWidgetArea)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/lucid/main_window.py", line 309, in add_dock
    self.dock_manager.addDockWidget(area, dock)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/embedded_display.py", line 308, in showEvent
    w = self.open_file()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/embedded_display.py", line 172, in open_file
    w = load_file(fname, macros=self.parsed_macros(), target=None)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/display.py", line 63, in load_file
    w = load_ui_file(file, macros=macros)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/display.py", line 111, in load_ui_file
    setupUi(d, d)
  File "<string>", line 70, in setupUi
  File "<string>", line 84, in retranslateUi
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/template_repeater.py", line 306, in dataSource
    self.data = json.load(f)
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/template_repeater.py", line 422, in data
    self.rebuild()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/widgets/template_repeater.py", line 387, in rebuild
    pydm.data_plugins.establish_queued_connections()
  File "/reg/g/pcds/pyps/apps/dev/pythonpath/pydm/data_plugins/__init__.py", line 45, in establish_queued_connections
    while not len(__CONNECTION_QUEUE__) == 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by hhslepicka** [comment]
@klauer do you happen to know if inside of this screen there is an embedded with a template repeater inside?

**Comment by klauer** [comment]
Yes, there is

**Comment by klauer** [comment]
If that's problematic, I may just expand it out statically and remove the repeater/embedded display

**Comment by hhslepicka** [comment]
I "guessed" that because of the error. It is clearly something on the PyDM side. On the connection queue. I believe that since the TemplateRepeater uses the queued connection and the PyDMEmbeddedDisplay tries to do some "smarts" about it, it may be causing this issue. I will take a look into that right now.

**Comment by hhslepicka** [comment]
I am transferring this issue to PyDM since I was able to recreate the problem via using PyDMEmbeddedDisplay and PyDMTemplateRepeater. I am trying now a possible patch for it.
